import type { BackgroundState, ShaderBgId } from '@/mockup/types'
import { BASE_LAYOUT, SHOTS_TEMPLATES } from './presets'
import type { Layout2D, MockupState, ShotsTemplate, TextState2D } from './types'

/* ------------------------------------------------------------------ */
/* Builders                                                            */
/* ------------------------------------------------------------------ */

const bgBase: BackgroundState = { kind: 'solid', colors: ['#ffffff'], angle: 135, noise: 0, image: null, imageBlur: 0.4, shader: 'mesh', speed: 0.3 }
const solid = (c: string, noise = 0): BackgroundState => ({ ...bgBase, kind: 'solid', colors: [c], noise })
const lin = (colors: string[], angle = 135, noise = 0): BackgroundState => ({ ...bgBase, kind: 'linear', colors, angle, noise })
const rad = (colors: string[]): BackgroundState => ({ ...bgBase, kind: 'radial', colors })
const shader = (id: ShaderBgId, colors: string[], speed = 0.3): BackgroundState => ({ ...bgBase, kind: 'shader', shader: id, colors, speed })

const L = (patch: Partial<Layout2D>): Layout2D => ({ ...BASE_LAYOUT, ...patch })

const phone = (model = 'iphone-17-pro', finish: MockupState['finish'] = 'silver', extra: Partial<MockupState> = {}): Partial<MockupState> => ({ kind: 'phone', model, finish, shadow: 'spread', ...extra })
const browser = (style: MockupState['browserStyle'] = 'safari', dark = false, extra: Partial<MockupState> = {}): Partial<MockupState> => ({ kind: 'browser', browserStyle: style, browserDark: dark, radius: 18, shadow: 'spread', ...extra })
const shot = (style: MockupState['style'] = 'default', extra: Partial<MockupState> = {}): Partial<MockupState> => ({ kind: 'screenshot', style, radius: 20, shadow: 'spread', ...extra })
const laptop = (model = 'macbook-pro-14', finish: MockupState['finish'] = 'space-black', extra: Partial<MockupState> = {}): Partial<MockupState> => ({ kind: 'laptop', model, finish, shadow: 'spread', ...extra })

const DARK_TEXT: Partial<TextState2D> = { color: '#0a0a0a', subColor: '#52525b', badgeText: '#ffffff' }
const LIGHT_TEXT: Partial<TextState2D> = { color: '#ffffff', subColor: '#d4d4d8', badgeText: '#0a0a0a' }
const BOLD: Partial<TextState2D> = { font: 'Inter', bodyFont: 'Inter', weight: 800, spacing: -3, lineHeight: 1.04, uppercase: false, highlight: 'color' }
const SERIF: Partial<TextState2D> = { font: 'Instrument Serif', bodyFont: 'Inter', weight: 400, spacing: -1, lineHeight: 1.0, uppercase: false, highlight: 'italic' }
const GROTESK: Partial<TextState2D> = { font: 'Space Grotesk', bodyFont: 'Space Grotesk', weight: 600, spacing: -3, lineHeight: 1.04, uppercase: false, highlight: 'marker' }
const CAPS: Partial<TextState2D> = { font: 'Bebas Neue', bodyFont: 'DM Sans', weight: 400, spacing: 1, lineHeight: 0.92, uppercase: true, highlight: 'color' }
const GEO: Partial<TextState2D> = { font: 'Sora', bodyFont: 'Manrope', weight: 700, spacing: -2, lineHeight: 1.06, uppercase: false, highlight: 'underline' }
const MONO: Partial<TextState2D> = { font: 'JetBrains Mono', bodyFont: 'JetBrains Mono', weight: 700, spacing: -4, lineHeight: 1.1, uppercase: false, highlight: 'marker' }
const FRIENDLY: Partial<TextState2D> = { font: 'Nunito', bodyFont: 'Nunito', weight: 800, spacing: -1, lineHeight: 1.06, uppercase: false, highlight: 'marker' }
const CLASSIC: Partial<TextState2D> = { font: 'Playfair Display', bodyFont: 'Lora', weight: 700, spacing: -1, lineHeight: 1.05, uppercase: false, highlight: 'italic' }

const text = (placement: TextState2D['placement'], copy: Partial<TextState2D>, ...styles: Partial<TextState2D>[]): Partial<TextState2D> => ({
  placement,
  eyebrow: '',
  subtitle: '',
  badge: '',
  align: placement === 'left' || placement === 'right' ? 'left' : 'center',
  ...Object.assign({}, ...styles),
  ...copy,
})

const APP_STORE = { width: 1290, height: 2796 }
const IPAD_STORE = { width: 2064, height: 2752 }
const PLAY_STORE = { width: 1080, height: 1920 }
const IG_POST = { width: 1080, height: 1350 }
const IG_STORY = { width: 1080, height: 1920 }
const SQUARE = { width: 1080, height: 1080 }
const X_POST = { width: 1600, height: 900 }
const LINKEDIN = { width: 1200, height: 627 }
const YT_THUMB = { width: 1280, height: 720 }
const PRODUCT_HUNT = { width: 1270, height: 760 }
const OG = { width: 1200, height: 630 }
const HD = { width: 1920, height: 1080 }
const DRIBBBLE = { width: 1600, height: 1200 }
const PIN = { width: 1000, height: 1500 }

/* ------------------------------------------------------------------ */
/* Library                                                             */
/* ------------------------------------------------------------------ */

export const EXTRA_TEMPLATES: ShotsTemplate[] = [
  /* ---------------- App Store / Play Store ---------------- */
  {
    id: 'as-warm',
    name: 'App Store · Warm',
    tag: 'App Store',
    category: 'app-store',
    description: 'Peach gradient, bold headline, phone bleeding off the bottom',
    mockup: phone('iphone-17-pro', 'cosmic-orange'),
    frame: { ...APP_STORE, background: lin(['#fff4ec', '#ffd9c4'], 180) },
    text: text('top', { eyebrow: 'Budgeting', headline: 'Track every *dollar* effortlessly', subtitle: 'See where your money goes, in real time.', area: 0.27, size: 7.4, accent: '#e05d38' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-midnight',
    name: 'App Store · Midnight',
    tag: 'App Store',
    category: 'app-store',
    description: 'Deep navy with a marker-highlighted headline',
    mockup: phone('iphone-17-pro', 'deep-blue'),
    frame: { ...APP_STORE, background: lin(['#0b1226', '#020617'], 180) },
    text: text('top', { eyebrow: 'Focus mode', headline: 'Do your *best work* without the noise', subtitle: 'Block distractions with one tap.', area: 0.28, size: 7, accent: '#3b82f6', badgeText: '#ffffff' }, GROTESK, LIGHT_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-editorial',
    name: 'App Store · Editorial',
    tag: 'App Store',
    category: 'app-store',
    description: 'Cream paper, serif headline with an italic accent',
    mockup: phone('iphone-air', 'light-gold', { shadow: 'hug', shadowOpacity: 0.45 }),
    frame: { ...APP_STORE, background: solid('#f4eee4', 0.18) },
    text: text('top', { eyebrow: 'Reading list', headline: 'Read more, *remember* more', subtitle: 'Highlights and notes that sync everywhere.', area: 0.27, size: 9, accent: '#b45309' }, SERIF, DARK_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-mint',
    name: 'App Store · Mint',
    tag: 'App Store',
    category: 'app-store',
    description: 'Fresh mint gradient, friendly rounded type',
    mockup: phone('iphone-17', 'sage'),
    frame: { ...APP_STORE, background: lin(['#ecfdf5', '#a7f3d0'], 180) },
    text: text('top', { eyebrow: 'Habits', headline: 'Build habits that *stick*', subtitle: 'Tiny daily wins, tracked beautifully.', area: 0.27, size: 7.6, accent: '#059669', badgeText: '#ffffff' }, FRIENDLY, { color: '#064e3b', subColor: '#047857' }),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-bottom',
    name: 'App Store · Caption below',
    tag: 'App Store',
    category: 'app-store',
    description: 'Phone drops in from the top, caption underneath',
    mockup: phone('iphone-17-pro', 'silver'),
    frame: { ...APP_STORE, background: lin(['#ede9fe', '#c4b5fd'], 160) },
    text: text('bottom', { headline: 'Plan your week in *minutes*', subtitle: 'Drag, drop, done.', area: 0.24, size: 7.2, accent: '#7c3aed' }, BOLD, { color: '#1e1b4b', subColor: '#4c1d95' }),
    base: L({ zoom: 1.12, y: 0.12 }),
  },
  {
    id: 'as-aurora-tilt',
    name: 'App Store · Aurora',
    tag: 'App Store',
    category: 'app-store',
    description: 'Tilted phone over a moving aurora',
    mockup: phone('iphone-17-pro', 'deep-blue', { shadow: 'adaptive', shadowOpacity: 0.7 }),
    frame: { ...APP_STORE, background: shader('aurora', ['#050816', '#22d3a6', '#7c3aed']) },
    text: text('top', { eyebrow: 'Sleep', headline: 'Wake up *rested*', subtitle: 'Smart alarms that follow your sleep cycle.', area: 0.25, size: 8, accent: '#5eead4' }, GEO, LIGHT_TEXT),
    base: L({ zoom: 1.0, y: -0.04, rotateZ: -7 }),
  },
  {
    id: 'as-duo',
    name: 'App Store · Duo',
    tag: 'App Store',
    category: 'app-store',
    description: 'Two screens side by side under one headline',
    mockup: phone('iphone-17', 'white', { count: 2, gap: 0.05 }),
    frame: { ...APP_STORE, background: lin(['#fef3c7', '#fde68a'], 180) },
    text: text('top', { eyebrow: 'Recipes', headline: 'Cook something *new* tonight', subtitle: 'Step-by-step, hands-free.', area: 0.36, size: 9, accent: '#d97706' }, BOLD, { color: '#422006', subColor: '#92400e' }),
    base: L({ zoom: 1.1, y: 0.02 }),
  },
  {
    id: 'as-bigtype',
    name: 'App Store · Big type',
    tag: 'App Store',
    category: 'app-store',
    description: 'Huge display caps on black, electric yellow accent',
    mockup: phone('iphone-17-pro', 'space-black', { shadow: 'adaptive', shadowOpacity: 0.6 }),
    frame: { ...APP_STORE, background: solid('#0a0a0a', 0.12) },
    text: text('top', { headline: 'Train *harder*\nrecover faster', area: 0.3, size: 13, accent: '#facc15' }, CAPS, LIGHT_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-glass',
    name: 'App Store · Glass',
    tag: 'App Store',
    category: 'app-store',
    description: 'Soft pastel glass gradient that moves in video',
    mockup: phone('iphone-17-pro', 'silver'),
    frame: { ...APP_STORE, background: shader('mesh', ['#fbcfe8', '#c7d2fe', '#a5f3fc'], 0.3) },
    text: text('top', { eyebrow: 'Journal', headline: 'A calmer place to *think*', subtitle: 'Private, encrypted, yours.', area: 0.27, size: 7.4, accent: '#6366f1' }, GEO, { color: '#1e1b4b', subColor: '#4338ca' }),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-ipad',
    name: 'App Store · iPad',
    tag: 'App Store',
    category: 'app-store',
    description: 'iPad Pro under a centred headline (2064×2752)',
    mockup: { kind: 'tablet', model: 'ipad-pro-13', finish: 'space-black', shadow: 'spread' },
    frame: { ...IPAD_STORE, background: lin(['#f8fafc', '#e2e8f0'], 180) },
    text: text('top', { eyebrow: 'For iPad', headline: 'Your studio, *anywhere*', subtitle: 'Pencil-ready canvases with unlimited layers.', area: 0.24, size: 6.4, accent: '#e05d38' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'ps-pixel',
    name: 'Play Store · Pixel',
    tag: 'Play Store',
    category: 'app-store',
    description: 'Pixel phone on green for Google Play (1080×1920)',
    mockup: { kind: 'android', model: 'pixel-10-pro', finish: 'graphite', shadow: 'spread' },
    frame: { ...PLAY_STORE, background: lin(['#dcfce7', '#86efac'], 180) },
    text: text('top', { headline: 'Split bills *instantly*', subtitle: 'No more awkward maths.', area: 0.25, size: 8, accent: '#15803d' }, FRIENDLY, { color: '#052e16', subColor: '#166534' }),
    base: L({ zoom: 1.14, y: -0.05 }),
  },
  {
    id: 'as-serif-dark',
    name: 'App Store · Noir',
    tag: 'App Store',
    category: 'app-store',
    description: 'Classic serif on charcoal, gold accent',
    mockup: phone('iphone-17-pro-max', 'space-black'),
    frame: { ...APP_STORE, background: rad(['#27272a', '#09090b']) },
    text: text('top', { eyebrow: 'Wine notes', headline: 'Every bottle, *remembered*', subtitle: 'Snap a label. Get the story.', area: 0.27, size: 7.6, accent: '#d4a656' }, CLASSIC, LIGHT_TEXT),
    base: L({ zoom: 1.14, y: -0.05 }),
  },

  /* ---------------- Social ---------------- */
  {
    id: 'ig-launch',
    name: 'Instagram · Launch post',
    tag: 'Instagram 4:5',
    category: 'social',
    description: 'Headline on top, browser window below',
    mockup: browser('safari', false),
    frame: { ...IG_POST, background: lin(['#fde68a', '#fca5a5', '#c4b5fd'], 150) },
    text: text('top', { eyebrow: 'Just shipped', headline: 'The fastest way to *share* a screenshot', area: 0.3, size: 7.6, accent: '#be123c' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.08, y: -0.04 }),
  },
  {
    id: 'ig-story',
    name: 'Instagram · Story',
    tag: 'Story 9:16',
    category: 'social',
    description: 'Phone rising from the bottom, caption and a badge',
    mockup: phone('iphone-17-pro', 'cosmic-orange'),
    frame: { ...IG_STORY, background: shader('mesh', ['#fb7185', '#818cf8', '#fcd34d'], 0.4) },
    text: text('top', { headline: 'New in the app: *dark mode*', badge: 'Update now', area: 0.24, size: 8.4, accent: '#111827', badgeText: '#ffffff' }, GROTESK, { color: '#ffffff', subColor: '#ffffff' }),
    base: L({ zoom: 1.12, y: -0.14 }),
  },
  {
    id: 'ig-square',
    name: 'Instagram · Square',
    tag: 'Square',
    category: 'social',
    description: 'Glass screenshot with a caption below',
    mockup: shot('glass-light', { radius: 24 }),
    frame: { ...SQUARE, background: shader('mesh', ['#f43f5e', '#8b5cf6', '#22d3ee'], 0.45) },
    text: text('bottom', { headline: 'Design *reviews* in one link', area: 0.22, size: 7, accent: '#fde047' }, BOLD, LIGHT_TEXT),
    base: L({ zoom: 1.0, y: 0.02 }),
  },
  {
    id: 'x-split',
    name: 'X · Split',
    tag: 'X 16:9',
    category: 'social',
    description: 'Copy on the left, MacBook on the right',
    mockup: laptop('macbook-pro-14', 'silver'),
    frame: { ...X_POST, background: lin(['#f8fafc', '#e0e7ff'], 135) },
    text: text('left', { eyebrow: 'Changelog', headline: 'Comments are *here*', subtitle: 'Leave feedback right on the canvas.', area: 0.42, size: 9, accent: '#4f46e5' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.08 }),
  },
  {
    id: 'x-dark',
    name: 'X · Dark split',
    tag: 'X 16:9',
    category: 'social',
    description: 'Phone on the left, bold copy on the right, near-black',
    mockup: phone('iphone-17-pro', 'deep-blue', { shadow: 'adaptive', shadowOpacity: 0.6 }),
    frame: { ...X_POST, background: rad(['#1f2937', '#030712']) },
    text: text('right', { eyebrow: 'iOS 26 ready', headline: 'Widgets that *actually* help', subtitle: 'Glanceable, live, and fully customisable.', area: 0.5, size: 8.6, accent: '#38bdf8' }, GEO, LIGHT_TEXT),
    base: L({ zoom: 0.94, rotateZ: 4 }),
  },
  {
    id: 'li-banner',
    name: 'LinkedIn · Announcement',
    tag: 'LinkedIn',
    category: 'social',
    description: 'Professional blue, copy left and a browser right',
    mockup: browser('chrome', false),
    frame: { ...LINKEDIN, background: lin(['#eff6ff', '#bfdbfe'], 135) },
    text: text('left', { eyebrow: "We're hiring", headline: 'Build the future of *team docs*', badge: 'See open roles', area: 0.44, size: 8.6, accent: '#1d4ed8' }, BOLD, { color: '#0f172a', subColor: '#334155', badgeText: '#ffffff' }),
    base: L({ zoom: 1.12, x: 0.06, rotateY: -14, rotateX: 4 }),
  },
  {
    id: 'li-carousel',
    name: 'LinkedIn · Carousel tip',
    tag: 'Carousel 4:5',
    category: 'social',
    description: 'Tip number, punchy headline, bordered screenshot',
    mockup: shot('border', { borderColor: '#ffffff', borderWidth: 12, radius: 18 }),
    frame: { ...IG_POST, background: solid('#111827', 0.1) },
    text: text('top', { eyebrow: 'Tip 03 / 07', headline: 'Use *shortcuts* to move 3× faster', area: 0.32, size: 7.4, accent: '#f59e0b' }, GROTESK, LIGHT_TEXT, { badgeText: '#111827' }),
    base: L({ zoom: 1.04, y: -0.02 }),
  },
  {
    id: 'yt-thumb',
    name: 'YouTube · Thumbnail',
    tag: 'Thumbnail',
    category: 'social',
    description: 'Shouty caps on yellow, tilted laptop',
    mockup: laptop('macbook-pro-16', 'space-black', { shadowOpacity: 0.6 }),
    frame: { ...YT_THUMB, background: solid('#facc15', 0.1) },
    text: text('left', { headline: 'I built this in *1 day*', area: 0.46, size: 15, accent: '#dc2626' }, CAPS, { color: '#0a0a0a', subColor: '#0a0a0a' }),
    base: L({ zoom: 1.12, x: 0.06, rotateY: -22, rotateX: 8, rotateZ: -4 }),
  },
  {
    id: 'pin-tall',
    name: 'Pinterest · Tall',
    tag: 'Pinterest 2:3',
    category: 'social',
    description: 'Three phones under an editorial headline',
    mockup: phone('iphone-17', 'lavender', { count: 3, gap: 0.04 }),
    frame: { ...PIN, background: solid('#f5f0ff', 0.12) },
    text: text('top', { eyebrow: 'Template pack', headline: '30 *aesthetic* home screens', area: 0.3, size: 8.4, accent: '#7c3aed' }, SERIF, DARK_TEXT),
    base: L({ zoom: 1.0, y: -0.02 }),
  },
  {
    id: 'dribbble-shapes',
    name: 'Dribbble shot',
    tag: 'Dribbble 4:3',
    category: 'social',
    description: 'Tilted screenshot among soft shapes, no text',
    mockup: shot('default', { radius: 22 }),
    frame: { ...DRIBBBLE, background: solid('#f4f4f5'), scene: 'shapes', shapesSeed: 23 },
    base: L({ zoom: 0.9, rotateX: 8, rotateY: -16, rotateZ: 3 }),
  },

  /* ---------------- Launch ---------------- */
  {
    id: 'ph-launch',
    name: 'Product Hunt · Launch',
    tag: 'Product Hunt',
    category: 'launch',
    description: '“Launching today” badge, copy left, tilted browser',
    mockup: browser('arc', false),
    frame: { ...PRODUCT_HUNT, background: lin(['#fff7ed', '#fed7aa'], 135) },
    text: text('left', { eyebrow: 'Launching today', headline: 'Mockups in *seconds*', subtitle: 'Drop a screenshot. Get a hero image.', badge: 'Upvote on Product Hunt', area: 0.44, size: 9.6, accent: '#da552f' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.2, x: 0.12, rotateY: -18, rotateX: 6 }),
  },
  {
    id: 'og-image',
    name: 'Open Graph image',
    tag: 'OG 1200×630',
    category: 'launch',
    description: 'Headline up top, browser cropped at the bottom edge',
    mockup: browser('safari', false),
    frame: { ...OG, background: lin(['#ffffff', '#f1f5f9'], 180) },
    text: text('top', { headline: 'The *beautiful* way to show your product', area: 0.36, size: 7.6, accent: '#e05d38' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.3, y: -0.3 }),
  },
  {
    id: 'hero-laptop',
    name: 'Landing hero',
    tag: '16:9',
    category: 'launch',
    description: 'Big headline over a MacBook rising from the bottom',
    mockup: laptop('macbook-pro-16', 'space-black'),
    frame: { ...HD, background: rad(['#1e1b4b', '#020617']) },
    text: text('top', { eyebrow: 'Introducing Beveled 2', headline: 'Your screenshots, *studio grade*', area: 0.34, size: 7.4, accent: '#a78bfa' }, GEO, LIGHT_TEXT),
    base: L({ zoom: 1.55, y: -0.34 }),
  },
  {
    id: 'now-live',
    name: 'Now live',
    tag: 'Launch',
    category: 'launch',
    description: 'Aurora, marker headline, browser beneath',
    mockup: browser('arc', true, { shadow: 'adaptive', shadowOpacity: 0.7 }),
    frame: { ...HD, background: shader('aurora', ['#050816', '#22d3a6', '#7c3aed']) },
    text: text('top', { eyebrow: 'Now live', headline: 'Say hello to *Canvas*', area: 0.28, size: 7.2, accent: '#22d3a6', badgeText: '#022c22' }, GROTESK, LIGHT_TEXT),
    base: L({ zoom: 1.1, y: -0.06 }),
  },
  {
    id: 'waitlist',
    name: 'Waitlist',
    tag: 'Launch',
    category: 'launch',
    description: 'Serif headline and a “Join the waitlist” pill',
    mockup: shot('inset-light', { radius: 22 }),
    frame: { ...HD, background: solid('#efe7dc', 0.18) },
    text: text('left', { eyebrow: 'Coming soon', headline: 'Email, *finally* calm', subtitle: 'An inbox that sorts itself.', badge: 'Join the waitlist', area: 0.42, size: 10, accent: '#1c1917', badgeText: '#ffffff' }, SERIF, { color: '#1c1917', subColor: '#57534e' }),
    base: L({ zoom: 1.08 }),
  },
  {
    id: 'version-2',
    name: 'Version 2.0',
    tag: 'Launch',
    category: 'launch',
    description: 'Display caps, isometric MacBook',
    mockup: laptop('macbook-air-13', 'midnight'),
    frame: { ...HD, background: lin(['#0f172a', '#1e293b'], 160) },
    text: text('left', { eyebrow: 'Version 2.0', headline: 'Faster. *Lighter.* Yours.', area: 0.42, size: 13, accent: '#f97316' }, CAPS, LIGHT_TEXT),
    base: L({ zoom: 1.0, x: 0.05, rotateX: 38, rotateZ: 28 }),
  },
  {
    id: 'press-display',
    name: 'Press kit',
    tag: 'Launch',
    category: 'launch',
    description: 'Studio Display on white with a quiet caption',
    mockup: { kind: 'monitor', model: 'studio-display', finish: 'silver', shadow: 'hug', shadowOpacity: 0.45 },
    frame: { ...HD, background: lin(['#ffffff', '#f4f4f5'], 180) },
    text: text('bottom', { headline: 'Designed for *teams* that ship', area: 0.17, size: 4.6, accent: '#e05d38' }, GEO, DARK_TEXT),
    base: L({ zoom: 1.0 }),
  },

  /* ---------------- Feature announcements ---------------- */
  {
    id: 'feat-new',
    name: 'New feature',
    tag: 'Feature',
    category: 'feature',
    description: '“New” eyebrow, copy left, zoomed-in screenshot right',
    mockup: shot('default', { radius: 18, shadow: 'spread' }),
    frame: { ...HD, background: lin(['#fdf2f8', '#fbcfe8'], 135) },
    text: text('left', { eyebrow: 'New', headline: 'Introducing *Smart Search*', subtitle: 'Find anything in your workspace in milliseconds.', area: 0.4, size: 9, accent: '#db2777' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.7, x: 0.42, y: -0.32 }),
  },
  {
    id: 'feat-changelog',
    name: 'Changelog',
    tag: 'Feature',
    category: 'feature',
    description: 'Dated eyebrow, inset screenshot, neutral palette',
    mockup: shot('inset-light', { radius: 20 }),
    frame: { ...HD, background: solid('#f5f5f4') },
    text: text('top', { eyebrow: 'Changelog · October', headline: 'Bulk edit, *keyboard first*', area: 0.24, size: 6, accent: '#ea580c' }, GROTESK, DARK_TEXT, { badgeText: '#ffffff' }),
    base: L({ zoom: 1.12, y: -0.12 }),
  },
  {
    id: 'feat-tip',
    name: 'Pro tip',
    tag: 'Feature',
    category: 'feature',
    description: 'Marker highlight, white-bordered screenshot on blue',
    mockup: shot('border', { borderColor: '#ffffff', borderWidth: 14, radius: 16 }),
    frame: { ...HD, background: lin(['#2563eb', '#1e40af'], 160) },
    text: text('left', { eyebrow: 'Pro tip', headline: 'Press */* to do *anything*', subtitle: 'The command palette is always one key away.', area: 0.4, size: 9, accent: '#fde047', badgeText: '#1e3a8a' }, GROTESK, LIGHT_TEXT),
    base: L({ zoom: 1.05, rotateY: -10 }),
  },
  {
    id: 'feat-compare',
    name: 'Before / after',
    tag: 'Feature',
    category: 'feature',
    description: 'Two screenshots side by side under a headline',
    mockup: shot('default', { count: 2, gap: 0.05, radius: 16 }),
    frame: { ...HD, background: lin(['#f1f5f9', '#e2e8f0'], 180) },
    text: text('top', { headline: 'Before → *after*', subtitle: 'Same data, half the clicks.', area: 0.26, size: 6.4, accent: '#16a34a' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.0 }),
  },
  {
    id: 'feat-mobile',
    name: 'Mobile feature',
    tag: 'Feature',
    category: 'feature',
    description: 'Copy left, phone right, warm sand',
    mockup: phone('iphone-17-pro', 'silver', { shadow: 'hug', shadowOpacity: 0.5 }),
    frame: { ...HD, background: solid('#efe2d0', 0.15), scene: 'shadow', lightShadowPattern: 'leaves', lightShadowOpacity: 0.35 },
    text: text('left', { eyebrow: 'On the go', headline: 'Approve requests *from anywhere*', subtitle: 'Push notifications with one-tap actions.', area: 0.5, size: 8, accent: '#9a3412' }, SERIF, { color: '#292524', subColor: '#57534e' }),
    base: L({ zoom: 1.0, rotateZ: -6 }),
  },
  {
    id: 'feat-code',
    name: 'Developer feature',
    tag: 'Feature',
    category: 'feature',
    description: 'Mono type, dark Chrome window, terminal green',
    mockup: browser('chrome', true, { shadow: 'adaptive', shadowOpacity: 0.55 }),
    frame: { ...HD, background: solid('#0a0a0a', 0.15) },
    text: text('top', { eyebrow: '$ npm i beveled', headline: 'Typed SDK, *zero config*', area: 0.26, size: 7, accent: '#22c55e', badgeText: '#052e16' }, MONO, LIGHT_TEXT),
    base: L({ zoom: 1.12, y: -0.1 }),
  },
  {
    id: 'feat-stat',
    name: 'Big number',
    tag: 'Feature',
    category: 'feature',
    description: 'Huge stat headline, screenshot tilted alongside',
    mockup: shot('glass-light', { radius: 22 }),
    frame: { ...HD, background: shader('mesh', ['#fed7aa', '#fecdd3', '#fef08a']) },
    text: text('left', { headline: '*3×* faster exports', subtitle: 'The new renderer, benchmarked on real projects.', area: 0.42, size: 12, accent: '#e11d48' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.05, rotateY: -16, rotateX: 6 }),
  },

  /* ---------------- Minimal ---------------- */
  {
    id: 'min-white',
    name: 'Pure white',
    tag: 'Minimal',
    category: 'minimal',
    description: 'White, soft spread shadow, nothing else',
    mockup: shot('default', { radius: 16, shadowOpacity: 0.35 }),
    frame: { ...HD, background: solid('#ffffff') },
    base: L({ zoom: 1.0 }),
  },
  {
    id: 'min-paper',
    name: 'Paper',
    tag: 'Minimal',
    category: 'minimal',
    description: 'Safari window on textured paper',
    mockup: browser('safari', false, { shadow: 'hug', shadowOpacity: 0.5 }),
    frame: { ...HD, background: solid('#ece6dc', 0.35) },
  },
  {
    id: 'min-outline',
    name: 'Outline',
    tag: 'Minimal',
    category: 'minimal',
    description: 'Black canvas, thin white outline',
    mockup: shot('outline', { borderColor: '#ffffff', radius: 20, shadow: 'none' }),
    frame: { ...HD, background: solid('#000000') },
    base: L({ zoom: 0.95 }),
  },
  {
    id: 'min-iso',
    name: 'Isometric grey',
    tag: 'Minimal',
    category: 'minimal',
    description: 'Screenshot laid flat at an isometric angle',
    mockup: shot('default', { radius: 18, shadowOpacity: 0.5 }),
    frame: { ...HD, background: solid('#e4e4e7') },
    base: L({ zoom: 0.95, rotateX: 42, rotateZ: 30 }),
  },
  {
    id: 'min-sand',
    name: 'Sand',
    tag: 'Minimal',
    category: 'minimal',
    description: 'Phone on warm sand with a tight shadow',
    mockup: phone('iphone-air', 'light-gold', { shadow: 'hug', shadowOpacity: 0.55 }),
    frame: { ...HD, background: solid('#e8dccb', 0.1) },
    base: L({ zoom: 1.0, rotateZ: 8 }),
  },
  {
    id: 'min-caption',
    name: 'Quiet caption',
    tag: 'Minimal',
    category: 'minimal',
    description: 'Screenshot with a small centred caption',
    mockup: shot('default', { radius: 14 }),
    frame: { ...HD, background: solid('#fafafa') },
    text: text('bottom', { headline: 'Dashboard · v3', area: 0.14, size: 3.2, accent: '#71717a' }, GEO, { color: '#3f3f46' }),
    base: L({ zoom: 1.0 }),
  },

  /* ---------------- Dark ---------------- */
  {
    id: 'dark-glow',
    name: 'Dark glow',
    tag: 'Dark',
    category: 'dark',
    description: 'Adaptive glow behind a dark browser',
    mockup: browser('chrome', true, { shadow: 'adaptive', shadowOpacity: 0.85 }),
    frame: { ...HD, background: solid('#050505'), grain: 0.06 },
  },
  {
    id: 'dark-prism',
    name: 'Prism',
    tag: 'Dark',
    category: 'dark',
    description: 'Glass-dark window on spectral rays',
    mockup: shot('glass-dark', { radius: 24 }),
    frame: { ...HD, background: shader('prism', ['#020617', '#111827', '#ffffff']), vignette: 0.3 },
    base: L({ zoom: 0.92 }),
  },
  {
    id: 'dark-headline',
    name: 'Dark headline',
    tag: 'Dark',
    category: 'dark',
    description: 'White serif headline, inset-dark screenshot',
    mockup: shot('inset-dark', { radius: 20, shadow: 'adaptive', shadowOpacity: 0.5 }),
    frame: { ...HD, background: rad(['#18181b', '#000000']) },
    text: text('top', { headline: 'Built for *the night shift*', area: 0.3, size: 10, accent: '#f472b6' }, SERIF, LIGHT_TEXT),
    base: L({ zoom: 1.12, y: -0.1 }),
  },
  {
    id: 'dark-chrome',
    name: 'Liquid chrome',
    tag: 'Dark',
    category: 'dark',
    description: 'Phone on liquid chrome with glow',
    mockup: phone('iphone-17-pro', 'space-black', { shadow: 'hug' }),
    frame: { ...HD, background: shader('chrome', ['#0a0a0a', '#d4d4d8', '#93c5fd']), bloom: 0.25 },
    base: L({ zoom: 1.0, rotateZ: -10 }),
  },

  /* ---------------- Glass ---------------- */
  {
    id: 'glass-frost',
    name: 'Frosted',
    tag: 'Glass',
    category: 'glass',
    description: 'Frosted glass frame on a vivid mesh',
    mockup: shot('glass-light', { radius: 28 }),
    frame: { ...HD, background: shader('mesh', ['#f43f5e', '#8b5cf6', '#22d3ee'], 0.45) },
    base: L({ zoom: 0.94 }),
  },
  {
    id: 'glass-liquid',
    name: 'Liquid glass',
    tag: 'Glass',
    category: 'glass',
    description: 'Liquid glass rim on aurora, tilted',
    mockup: shot('liquid-glass', { radius: 30, shadow: 'adaptive', shadowOpacity: 0.6 }),
    frame: { ...HD, background: shader('aurora', ['#050816', '#22d3a6', '#7c3aed']) },
    base: L({ zoom: 0.92, rotateX: 6, rotateY: 16 }),
  },
  {
    id: 'glass-headline',
    name: 'Glass + headline',
    tag: 'Glass',
    category: 'glass',
    description: 'Pastel glass with a geometric headline',
    mockup: shot('glass-light', { radius: 26 }),
    frame: { ...HD, background: shader('mesh', ['#fbcfe8', '#c7d2fe', '#a5f3fc']) },
    text: text('top', { headline: 'Clarity for *every* team', area: 0.24, size: 6.6, accent: '#4f46e5' }, GEO, { color: '#1e1b4b', subColor: '#4338ca' }),
    base: L({ zoom: 1.1, y: -0.1 }),
  },

  /* ---------------- Devices ---------------- */
  {
    id: 'dev-ipad-trio',
    name: 'iPad trio',
    tag: 'Devices',
    category: 'devices',
    description: 'Three iPads on a cool gradient',
    mockup: { kind: 'tablet', model: 'ipad-air', finish: 'starlight', count: 3, gap: 0.05, shadow: 'spread' },
    frame: { ...HD, background: lin(['#e0f2fe', '#c7d2fe'], 135) },
  },
  {
    id: 'dev-watch',
    name: 'Watch',
    tag: 'Devices',
    category: 'devices',
    description: 'Apple Watch Ultra with copy on the right',
    mockup: { kind: 'watch', model: 'watch-ultra', finish: 'titanium', shadow: 'hug' },
    frame: { ...HD, background: lin(['#fff7ed', '#fdba74'], 160) },
    text: text('right', { eyebrow: 'watchOS', headline: 'Your runs, *on your wrist*', subtitle: 'Live pace, heart rate and splits.', area: 0.48, size: 8, accent: '#c2410c' }, BOLD, { color: '#431407', subColor: '#9a3412' }),
    base: L({ zoom: 1.0 }),
  },
  {
    id: 'dev-macbook-sky',
    name: 'MacBook sky',
    tag: 'Devices',
    category: 'devices',
    description: 'Silver MacBook on a soft sky gradient',
    mockup: laptop('macbook-air-13', 'starlight'),
    frame: { ...HD, background: lin(['#e0f2fe', '#ffffff'], 180) },
  },
  {
    id: 'dev-phone-tilt',
    name: 'Phone tilt trio',
    tag: 'Devices',
    category: 'devices',
    description: 'Three phones turned in perspective',
    mockup: phone('iphone-17-pro', 'cosmic-orange', { count: 3, gap: 0.06 }),
    frame: { ...HD, background: solid('#111111') },
    base: L({ zoom: 0.92, rotateX: 8, rotateY: -26 }),
  },
  {
    id: 'dev-display',
    name: 'Studio Display',
    tag: 'Devices',
    category: 'devices',
    description: 'Pro Display XDR on a dark gradient',
    mockup: { kind: 'monitor', model: 'pro-display-xdr', finish: 'silver', shadow: 'spread' },
    frame: { ...HD, background: lin(['#334155', '#0f172a'], 180) },
  },

  /* ---------------- Animated ---------------- */
  {
    id: 'anim-hero-push',
    name: 'Hero push-in',
    tag: 'Animated',
    category: 'launch',
    animated: true,
    description: 'Headline fades up while the laptop pushes in',
    mockup: laptop('macbook-pro-14', 'space-black'),
    frame: { ...HD, background: rad(['#312e81', '#020617']) },
    text: text('top', { eyebrow: 'Now available', headline: 'Meet the *new* dashboard', area: 0.3, size: 7, accent: '#a5b4fc' }, GEO, LIGHT_TEXT),
    base: L({ zoom: 0.95, y: -0.02 }),
    steps: [{ layout: { zoom: 1.3, y: -0.3 }, duration: 2.4 }],
  },
  {
    id: 'anim-pan',
    name: 'Page pan',
    tag: 'Animated',
    category: 'feature',
    animated: true,
    description: 'Glides from the top-left of the page to the bottom-right',
    mockup: browser('safari', false),
    frame: { ...HD, background: lin(['#ecfeff', '#a5f3fc'], 135) },
    base: L({ zoom: 1.8, x: 0.42, y: -0.42 }),
    steps: [
      { layout: { zoom: 1.8, x: -0.42, y: 0.42 }, duration: 3 },
      { layout: { zoom: 1, x: 0, y: 0 }, duration: 1.4 },
    ],
  },
  {
    id: 'anim-spin-in',
    name: 'Spin in',
    tag: 'Animated',
    category: 'social',
    animated: true,
    description: 'Phone spins in from a steep angle under a caption',
    mockup: phone('iphone-17-pro', 'silver'),
    frame: { ...IG_STORY, background: shader('mesh', ['#fbcfe8', '#c7d2fe', '#a5f3fc']) },
    text: text('top', { headline: 'Swipe to *explore*', area: 0.22, size: 9, accent: '#6366f1' }, FRIENDLY, { color: '#1e1b4b' }),
    base: L({ zoom: 0.7, rotateY: 60, rotateZ: -20 }),
    steps: [{ layout: { zoom: 1.08, rotateY: 0, rotateZ: 0, y: -0.06 }, duration: 1.8 }],
  },
  {
    id: 'anim-rise',
    name: 'Rise up',
    tag: 'Animated',
    category: 'app-store',
    animated: true,
    description: 'Phone rises from below the frame into place',
    mockup: phone('iphone-17-pro', 'cosmic-orange'),
    frame: { ...APP_STORE, background: lin(['#fff4ec', '#ffd9c4'], 180) },
    text: text('top', { headline: 'Set up in *30 seconds*', area: 0.26, size: 8, accent: '#e05d38' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.12, y: -1.6 }),
    steps: [{ layout: { y: -0.1 }, duration: 1.6 }],
  },
  {
    id: 'anim-tour',
    name: 'Feature tour',
    tag: 'Animated',
    category: 'feature',
    animated: true,
    description: 'Copy on the left while the screenshot zooms through three spots',
    mockup: shot('default', { radius: 18 }),
    frame: { ...HD, background: solid('#f8fafc') },
    text: text('left', { eyebrow: 'Walkthrough', headline: 'Three steps to *launch*', area: 0.36, size: 8.4, accent: '#e05d38' }, BOLD, DARK_TEXT),
    base: L({ zoom: 1.0 }),
    steps: [
      { layout: { zoom: 1.9, x: 0.42, y: -0.4 }, duration: 1.4 },
      { layout: { zoom: 1.9, x: -0.4, y: -0.1 }, duration: 1.6 },
      { layout: { zoom: 1.9, x: 0.1, y: 0.4 }, duration: 1.6 },
      { layout: { zoom: 1, x: 0, y: 0 }, duration: 1.4 },
    ],
  },
  {
    id: 'anim-iso-flip',
    name: 'Iso flip',
    tag: 'Animated',
    category: 'dark',
    animated: true,
    description: 'Dark screenshot flips from isometric to face-on',
    mockup: shot('inset-dark', { radius: 20, shadow: 'adaptive', shadowOpacity: 0.6 }),
    frame: { ...HD, background: shader('swirl', ['#0b0614', '#7c3aed', '#f0abfc'], 0.25) },
    base: L({ zoom: 0.85, rotateX: 42, rotateZ: 30 }),
    steps: [{ layout: { zoom: 1, rotateX: 0, rotateZ: 0 }, duration: 2 }],
  },
]

export const TEMPLATE_CATEGORIES: { id: NonNullable<ShotsTemplate['category']>; label: string }[] = [
  { id: 'app-store', label: 'App Store' },
  { id: 'social', label: 'Social' },
  { id: 'launch', label: 'Launch' },
  { id: 'feature', label: 'Features' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'dark', label: 'Dark' },
  { id: 'glass', label: 'Glass' },
  { id: 'devices', label: 'Devices' },
]

/** Every 2-D template: the originals plus the text-led library above. */
export const ALL_TEMPLATES: ShotsTemplate[] = [...EXTRA_TEMPLATES, ...SHOTS_TEMPLATES]
