import type { BgPreset, LinearGradient, ShadowStrength, WindowStyle } from '@/components/app-sidebar'
import type { TextNode, ShapeNode } from './types'

export type EditorTemplate = {
  id: string
  name: string
  description?: string
  // Canvas/frame
  bg: BgPreset
  padding: { x: number; y: number }
  showWindow: boolean
  windowStyle: WindowStyle
  windowBarColor: string
  cornerRadius: number
  shadow: ShadowStrength
  // Content
  texts?: TextNode[]
  shapes?: ShapeNode[]
  // Behavior
  cropAspect?: number // width/height aspect to auto-crop screenshot
  imageScale?: number // optional preview scale factor (0..1)
  targetWidth?: number // alternative to imageScale
  dimContent?: number // 0..1 overlay alpha inside content area for contrast
  // Optional initial screenshot offset inside content area (CSS pixels)
  imageOffsetX?: number
  imageOffsetY?: number
  // Optional layout preset for deterministic placement
  layoutPreset?: 'right-accent' | 'bottom-center' | 'left-accent' | 'right-below-title'
}

const gradient = (angle: number, colors: string[]): LinearGradient => ({
  type: 'linear',
  angle,
  stops: colors.map((c, i) => ({ color: c, pos: i / Math.max(1, colors.length - 1) })),
})

export const TEMPLATES: EditorTemplate[] = [
  // Modern Blue Gradient
  {
    id: 'pro-center-stack-gradient',
    name: 'Modern Blue',
    description: 'Modern blue gradient with clean typography and perfect spacing.',
    bg: gradient(135, ['#667eea', '#764ba2']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1e293b',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'New Feature',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#1e293b',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'solid',
        backgroundColor: '#ffffff',
        backgroundAlpha: 0.95,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.1,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Beautiful Screenshots',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.25,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Create professional images',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f1f5f9',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  {
    id: 'pro-center-stack-light',
    name: 'Clean Minimal',
    description: 'Minimal light theme with elegant typography and perfect contrast.',
    bg: gradient(135, ['#fdfbfb', '#ebedee']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#374151',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Case Study',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'linear',
        backgroundColor: '#6366f1',
        backgroundColor2: '#8b5cf6',
        backgroundAngle: 135,
        backgroundAlpha: 1,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#6366f1',
        shadowAlpha: 0.3,
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Clean Design ',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'linear',
        color: '#1f2937',
        fillColor2: '#374151',
        fillAngle: 135,
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: false,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Beautiful interfaces that users love to interact with',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#6b7280',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: false,
      },
    ],
  },

  {
    id: 'pro-center-stack-grid-dark',
    name: 'Dark Grid Pro',
    description: 'Professional dark grid theme with modern typography and perfect spacing.',
    bg: { type: 'pattern', name: 'grid', fg: '#1e293b', bg: '#0f172a', scale: 32 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#111827',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Premium',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#0f172a',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'linear',
        backgroundColor: '#fbbf24',
        backgroundColor2: '#f59e0b',
        backgroundAngle: 135,
        backgroundAlpha: 1,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#f59e0b',
        shadowAlpha: 0.4,
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Next-Level Screenshot Editor',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f8fafc',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.3,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Create content that stands out from the crowd',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#cbd5e1',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },
  {
    id: 'pro-left-hero',
    name: 'Ocean Breeze',
    description: 'Fresh ocean-inspired gradient with modern typography and clean layout.',
    bg: gradient(135, ['#667eea', '#764ba2']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1e293b',
    cornerRadius: 16,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Launch Week',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#1e293b',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'solid',
        backgroundColor: '#ffffff',
        backgroundAlpha: 0.95,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.1,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Revolutionary Design Tools',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.25,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Transform your workflow with powerful features',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f1f5f9',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  {
    id: 'pro-center-hero',
    name: 'Cosmic Purple',
    description: 'Vibrant cosmic gradient with bold typography and modern aesthetics.',
    bg: gradient(135, ['#a855f7', '#ec4899']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1e293b',
    cornerRadius: 18,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Open Source',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#1e293b',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'solid',
        backgroundColor: '#ffffff',
        backgroundAlpha: 0.95,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.1,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Creative Freedom Unleashed',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.25,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Express your ideas with unlimited possibilities',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f1f5f9',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  {
    id: 'pro-dark-minimal',
    name: 'Midnight Grid',
    description: 'Sleek midnight theme with subtle grid pattern and elegant typography.',
    bg: { type: 'pattern', name: 'grid', fg: '#1e293b', bg: '#0f172a', scale: 32 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#111827',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Developer',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#0f172a',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'linear',
        backgroundColor: '#10b981',
        backgroundColor2: '#059669',
        backgroundAngle: 135,
        backgroundAlpha: 1,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#10b981',
        shadowAlpha: 0.4,
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Code That Inspires',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f8fafc',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.3,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Building the future, one line at a time',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#cbd5e1',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  {
    id: 'pro-right-accent',
    name: 'Sky Dreams',
    description: 'Dreamy sky gradient with inspiring typography and perfect balance.',
    bg: gradient(135, ['#38bdf8', '#7c3aed']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1e293b',
    cornerRadius: 16,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Innovation',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#1e293b',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'solid',
        backgroundColor: '#ffffff',
        backgroundAlpha: 0.95,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.1,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Innovation Meets Design',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.25,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Where creativity meets cutting-edge technology',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f1f5f9',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  {
    id: 'pro-light-neutral',
    name: 'Pure Elegance',
    description: 'Pure and elegant light theme with sophisticated typography.',
    bg: gradient(135, ['#ffffff', '#f1f5f9']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#374151',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Showcase',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'linear',
        backgroundColor: '#1f2937',
        backgroundColor2: '#374151',
        backgroundAngle: 135,
        backgroundAlpha: 1,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#1f2937',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Elegant Simplicity',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'linear',
        color: '#1f2937',
        fillColor2: '#374151',
        fillAngle: 135,
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: false,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Where less becomes more and clarity shines',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#6b7280',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: false,
      },
    ],
  },

  {
    id: 'pro-text-focus',
    name: 'Forest Fresh',
    description: 'Fresh forest gradient with natural vibes and clean typography.',
    bg: gradient(135, ['#10b981', '#14b8a6']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1e293b',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      {
        id: 'tag',
        positionAnchor: 'stage',
        x: 720,
        y: 60,
        text: 'Eco-Friendly',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 14,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#1e293b',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: true,
        backgroundType: 'solid',
        backgroundColor: '#ffffff',
        backgroundAlpha: 0.95,
        backgroundPaddingX: 18,
        backgroundPaddingY: 8,
        backgroundRadius: 999,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.1,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
      {
        id: 'title',
        positionAnchor: 'stage',
        x: 720,
        y: 110,
        text: 'Sustainable Solutions',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 56,
        bold: true,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#ffffff',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.25,
        shadowBlur: 16,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: 'subtitle',
        positionAnchor: 'stage',
        x: 720,
        y: 180,
        text: 'Building a better tomorrow, naturally',
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
        fontSize: 20,
        bold: false,
        italic: false,
        align: 'center',
        fillType: 'solid',
        color: '#f1f5f9',
        outline: false,
        outlineColor: '#000000',
        outlineWidth: 0,
        background: false,
        shadow: true,
        shadowColor: '#000000',
        shadowAlpha: 0.2,
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
      },
    ],
  },

  // Aurora — rich 3-stop gradient
  {
    id: 'pro-aurora',
    name: 'Aurora',
    description: 'Teal → Violet → Pink aurora gradient with crisp typography.',
    bg: gradient(120, ['#06b6d4', '#7c3aed', '#ec4899']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#111827',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Aurora', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.95, backgroundPaddingX: 18, backgroundPaddingY: 8, backgroundRadius: 999, shadow: true, shadowColor: '#000000', shadowAlpha: 0.1, shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2 },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Paint With Light', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.25, shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Vivid gradients for modern UI', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#f1f5f9', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.2, shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2 },
    ],
  },

  // Sunset — warm 3-stop gradient
  {
    id: 'pro-sunset',
    name: 'Sunset',
    description: 'Orange → Rose → Violet sunset gradient with soft contrast.',
    bg: gradient(135, ['#f59e0b', '#f43f5e', '#8b5cf6']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1f2937',
    cornerRadius: 18,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Sunset', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#1f2937', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.95, backgroundPaddingX: 18, backgroundPaddingY: 8, backgroundRadius: 999, shadow: true, shadowColor: '#000000', shadowAlpha: 0.1, shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2 },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Warm & Welcoming', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.25, shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Create inviting product shots', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#f8fafc', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.2, shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2 },
    ],
  },

  // Noir Dots — subtle dark dot pattern
  {
    id: 'pro-noir-dots',
    name: 'Noir Dots',
    description: 'Subtle dark dot pattern for a premium minimal look.',
    bg: { type: 'pattern', name: 'dots', fg: '#ffffff10', bg: '#0b1220', scale: 26 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f172a',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Noir', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#cbd5e1', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#0f172a', backgroundAlpha: 0.9, backgroundPaddingX: 18, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Premium Minimal', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#f8fafc', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.3, shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Quiet texture, bold focus', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#94a3b8', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Blueprint Grid — airy light grid
  {
    id: 'pro-blueprint-grid',
    name: 'Blueprint Grid',
    description: 'Airy light blueprint-style grid for documentation and how-tos.',
    bg: { type: 'pattern', name: 'grid', fg: '#e2e8f0', bg: '#ffffff', scale: 28 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#374151',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Guide', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#1f2937', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#e5e7eb', backgroundAlpha: 1, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Crystal Clear Docs', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#111827', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Explain concepts at a glance', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#4b5563', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Mint Cream — super soft mint gradient
  {
    id: 'pro-mint-cream',
    name: 'Mint Cream',
    description: 'Soft mint gradient for clean, calm presentations.',
    bg: gradient(135, ['#ecfeff', '#ccfbf1']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f172a',
    cornerRadius: 18,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Calm', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.95, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'A Breath of Fresh Air', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Serene gradients for calm brands', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#334155', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Circuit Board — dark tech pattern
  {
    id: 'pro-circuit-board',
    name: 'Circuit Board',
    description: 'Dark tech look with circuit traces and crisp type.',
    bg: { type: 'pattern', name: 'circuit', fg: '#22c55e80', bg: '#0b1220', scale: 28 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f172a',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Engineering', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#22c55e', backgroundAlpha: 0.9, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Built for Builders', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#e2e8f0', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.35, shadowBlur: 18, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Precision visuals for technical products', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#a7f3d0', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Sprinkles — playful confetti lines
  {
    id: 'pro-sprinkles',
    name: 'Sprinkles',
    description: 'Playful sprinkles pattern with candy colors.',
    bg: { type: 'pattern', name: 'sprinkles', fg: '#f472b6', bg: '#fff7ed', scale: 28 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1f2937',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Launch', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#1f2937', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.95, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: true, shadowColor: '#000000', shadowAlpha: 0.08, shadowBlur: 6, shadowOffsetX: 0, shadowOffsetY: 2 },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Make It Delightful', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Friendly visuals that pop', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#334155', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Chevron Light — editorial texture
  {
    id: 'pro-chevron-light',
    name: 'Chevron Light',
    description: 'Editorial chevron texture over a clean canvas.',
    bg: { type: 'pattern', name: 'chevron', fg: '#e5e7eb', bg: '#fafaf9', scale: 28 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#374151',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Editorial', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#111827', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#e5e7eb', backgroundAlpha: 1, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Simply Sophisticated', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#111827', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'An understated, timeless feel', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#4b5563', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Starscape — night sky mood
  {
    id: 'pro-starscape',
    name: 'Starscape',
    description: 'Night-sky feel with star pattern and soft glow type.',
    bg: { type: 'pattern', name: 'stars', fg: '#ffffffaa', bg: '#0b1220', scale: 28 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f172a',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Night', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#0f172a', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.9, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Reach For The Stars', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#f8fafc', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#000000', shadowAlpha: 0.35, shadowBlur: 18, shadowOffsetX: 0, shadowOffsetY: 6 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Cosmic vibes for announcements', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#cbd5e1', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Hex Lines — geometric minimal
  {
    id: 'pro-hex-lines',
    name: 'Hex Lines',
    description: 'Geometric minimalism with a hex outline grid.',
    bg: { type: 'pattern', name: 'hex', fg: '#e5e7eb', bg: '#ffffff', scale: 26 },
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#374151',
    cornerRadius: 16,
    shadow: 'subtle',
    cropAspect: 16 / 9,
    targetWidth: 900,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    imageOffsetY: 300,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Geometry', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#111827', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#e5e7eb', backgroundAlpha: 1, backgroundPaddingX: 16, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Structured Elegance', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 56, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#111827', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Clean lines, crystal clarity', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#4b5563', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Cyberpunk Neon
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Dark theme with electric neon accents and futuristic typography.',
    bg: gradient(45, ['#0f0f23', '#1a1a2e', '#16213e']),
    padding: { x: 100, y: 100 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f0f23',
    cornerRadius: 16,
    shadow: 'strong',
    cropAspect: 16 / 9,
    targetWidth: 800,
    imageScale: 0.45,
    layoutPreset: 'right-accent',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 160, y: 60, text: 'TECH', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 12, bold: true, italic: false, align: 'left', fillType: 'solid', color: '#00ff88', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#00ff88', backgroundAlpha: 0.15, backgroundPaddingX: 12, backgroundPaddingY: 6, backgroundRadius: 4, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 160, y: 110, text: 'Neural Interface', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 48, bold: true, italic: false, align: 'left', fillType: 'linear', color: '#ffffff', fillColor2: '#00ff88', fillAngle: 90, outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#00ff88', shadowAlpha: 0.3, shadowBlur: 20, shadowOffsetX: 0, shadowOffsetY: 0 },
      { id: 'subtitle', positionAnchor: 'stage', x: 160, y: 180, text: 'Next-gen digital experience', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'left', fillType: 'solid', color: '#a0a0a0', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Warm Sunset
  {
    id: 'warm-sunset',
    name: 'Warm Sunset',
    description: 'Cozy warm gradient with elegant serif typography.',
    bg: gradient(135, ['#ff9a9e', '#fecfef', '#fecfef']),
    padding: { x: 90, y: 90 },
    showWindow: true,
    windowStyle: 'notch',
    windowBarColor: '#2d1b69',
    cornerRadius: 24,
    shadow: 'medium',
    cropAspect: 4 / 3,
    targetWidth: 750,
    imageScale: 0.5,
    layoutPreset: 'bottom-center',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'Design', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: false, italic: true, align: 'center', fillType: 'solid', color: '#2d1b69', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#ffffff', backgroundAlpha: 0.9, backgroundPaddingX: 20, backgroundPaddingY: 8, backgroundRadius: 999, shadow: true, shadowColor: '#ff9a9e', shadowAlpha: 0.2, shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Creative Flow', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 52, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#2d1b69', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#ffffff', shadowAlpha: 0.8, shadowBlur: 0, shadowOffsetX: 2, shadowOffsetY: 2 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Where inspiration meets execution', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 19, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#5b21b6', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Monochrome Professional
  {
    id: 'monochrome-pro',
    name: 'Monochrome Pro',
    description: 'Clean black and white with sophisticated typography.',
    bg: { type: 'solid', color: '#f8fafc' },
    padding: { x: 120, y: 120 },
    showWindow: false,
    windowStyle: 'regular',
    windowBarColor: '#000000',
    cornerRadius: 12,
    shadow: 'subtle',
    cropAspect: 16 / 10,
    targetWidth: 900,
    imageScale: 0.4,
    layoutPreset: 'right-accent',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 160, y: 60, text: 'PORTFOLIO', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 11, bold: true, italic: false, align: 'left', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#000000', backgroundAlpha: 1, backgroundPaddingX: 16, backgroundPaddingY: 6, backgroundRadius: 2, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 160, y: 110, text: 'Minimal Excellence', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 44, bold: true, italic: false, align: 'left', fillType: 'solid', color: '#000000', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 160, y: 180, text: 'Precision in every detail', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'left', fillType: 'solid', color: '#64748b', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Ocean Depths
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep blue gradient with flowing text and aquatic vibes.',
    bg: gradient(180, ['#1e3a8a', '#1e40af', '#3b82f6']),
    padding: { x: 80, y: 80 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#0f172a',
    cornerRadius: 20,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 850,
    imageScale: 0.45,
    layoutPreset: 'left-accent',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 960, y: 60, text: 'Fluid', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: false, italic: true, align: 'right', fillType: 'solid', color: '#60a5fa', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#1e40af', backgroundAlpha: 0.6, backgroundPaddingX: 18, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 960, y: 110, text: 'Deep Dive', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 50, bold: true, italic: false, align: 'right', fillType: 'linear', color: '#ffffff', fillColor2: '#60a5fa', fillAngle: 45, outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#1e40af', shadowAlpha: 0.4, shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 960, y: 180, text: 'Immersive experiences await', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'right', fillType: 'solid', color: '#bfdbfe', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Retro Synthwave
  {
    id: 'retro-synthwave',
    name: 'Retro Synthwave',
    description: '80s inspired with neon colors and retro-futuristic style.',
    bg: gradient(135, ['#2d1b69', '#11998e', '#38ef7d']),
    padding: { x: 100, y: 100 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#1a0933',
    cornerRadius: 16,
    shadow: 'strong',
    cropAspect: 16 / 9,
    targetWidth: 800,
    imageScale: 0.4,
    layoutPreset: 'bottom-center',
    imageOffsetY: 200,
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 720, y: 60, text: 'RETRO', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 12, bold: true, italic: false, align: 'center', fillType: 'solid', color: '#2d1b69', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'linear', backgroundColor: '#ff006e', backgroundColor2: '#ffbe0b', backgroundAngle: 45, backgroundAlpha: 1, backgroundPaddingX: 16, backgroundPaddingY: 6, backgroundRadius: 4, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 720, y: 110, text: 'Neon Dreams', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 54, bold: true, italic: false, align: 'center', fillType: 'linear', color: '#ff006e', fillColor2: '#ffbe0b', fillAngle: 45, outline: true, outlineColor: '#ffffff', outlineWidth: 2, background: false, shadow: true, shadowColor: '#ff006e', shadowAlpha: 0.6, shadowBlur: 20, shadowOffsetX: 0, shadowOffsetY: 0 },
      { id: 'subtitle', positionAnchor: 'stage', x: 720, y: 180, text: 'Synthwave aesthetic revival', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 20, bold: false, italic: false, align: 'center', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#2d1b69', shadowAlpha: 0.8, shadowBlur: 8, shadowOffsetX: 0, shadowOffsetY: 2 },
    ],
  },

  // Elegant Marble
  {
    id: 'elegant-marble',
    name: 'Elegant Marble',
    description: 'Sophisticated marble pattern with gold accents.',
    bg: { type: 'pattern', name: 'noise', fg: '#e5e7eb', bg: '#f8fafc', scale: 32 },
    padding: { x: 110, y: 110 },
    showWindow: true,
    windowStyle: 'title',
    windowBarColor: '#1f2937',
    cornerRadius: 18,
    shadow: 'medium',
    cropAspect: 4 / 3,
    targetWidth: 750,
    imageScale: 0.5,
    layoutPreset: 'right-below-title',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 160, y: 60, text: 'Luxury', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 13, bold: false, italic: true, align: 'left', fillType: 'solid', color: '#d97706', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'linear', backgroundColor: '#fbbf24', backgroundColor2: '#d97706', backgroundAngle: 135, backgroundAlpha: 0.15, backgroundPaddingX: 20, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 160, y: 110, text: 'Timeless Beauty', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 46, bold: true, italic: false, align: 'left', fillType: 'linear', color: '#1f2937', fillColor2: '#d97706', fillAngle: 90, outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
      { id: 'subtitle', positionAnchor: 'stage', x: 160, y: 180, text: 'Crafted with precision and care', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'left', fillType: 'solid', color: '#6b7280', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Forest Green
  {
    id: 'forest-green',
    name: 'Forest Green',
    description: 'Natural green tones with organic, earthy typography.',
    bg: gradient(135, ['#064e3b', '#065f46', '#047857']),
    padding: { x: 90, y: 90 },
    showWindow: true,
    windowStyle: 'regular',
    windowBarColor: '#022c22',
    cornerRadius: 22,
    shadow: 'medium',
    cropAspect: 16 / 9,
    targetWidth: 820,
    imageScale: 0.45,
    layoutPreset: 'right-accent',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 160, y: 60, text: 'Nature', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 14, bold: false, italic: false, align: 'left', fillType: 'solid', color: '#064e3b', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'solid', backgroundColor: '#6ee7b7', backgroundAlpha: 0.9, backgroundPaddingX: 18, backgroundPaddingY: 8, backgroundRadius: 999, shadow: false },
      { id: 'title', positionAnchor: 'stage', x: 160, y: 110, text: 'Organic Growth', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 48, bold: true, italic: false, align: 'left', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#022c22', shadowAlpha: 0.6, shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 160, y: 180, text: 'Sustainable innovation for tomorrow', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'left', fillType: 'solid', color: '#a7f3d0', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },

  // Cosmic Purple
  {
    id: 'cosmic-purple',
    name: 'Cosmic Purple',
    description: 'Deep space vibes with stellar purple gradients.',
    bg: gradient(225, ['#1e1b4b', '#3730a3', '#6366f1']),
    padding: { x: 100, y: 100 },
    showWindow: true,
    windowStyle: 'notch',
    windowBarColor: '#0f0f23',
    cornerRadius: 20,
    shadow: 'strong',
    cropAspect: 16 / 9,
    targetWidth: 850,
    imageScale: 0.4,
    layoutPreset: 'left-accent',
    texts: [
      { id: 'tag', positionAnchor: 'stage', x: 960, y: 60, text: 'Cosmic', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 12, bold: true, italic: false, align: 'right', fillType: 'solid', color: '#ffffff', outline: false, outlineColor: '#000000', outlineWidth: 0, background: true, backgroundType: 'linear', backgroundColor: '#8b5cf6', backgroundColor2: '#a855f7', backgroundAngle: 45, backgroundAlpha: 0.8, backgroundPaddingX: 16, backgroundPaddingY: 6, backgroundRadius: 999, shadow: true, shadowColor: '#8b5cf6', shadowAlpha: 0.4, shadowBlur: 12, shadowOffsetX: 0, shadowOffsetY: 2 },
      { id: 'title', positionAnchor: 'stage', x: 960, y: 110, text: 'Stellar Journey', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 50, bold: true, italic: false, align: 'right', fillType: 'linear', color: '#ffffff', fillColor2: '#c084fc', fillAngle: 135, outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: true, shadowColor: '#1e1b4b', shadowAlpha: 0.8, shadowBlur: 16, shadowOffsetX: 0, shadowOffsetY: 4 },
      { id: 'subtitle', positionAnchor: 'stage', x: 960, y: 180, text: 'Explore the infinite possibilities', fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', fontSize: 18, bold: false, italic: false, align: 'right', fillType: 'solid', color: '#c7d2fe', outline: false, outlineColor: '#000000', outlineWidth: 0, background: false, shadow: false },
    ],
  },
]
